spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.example.spring_rest_api: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080

app:
  upload:
    root: ${user.dir}/uploads

  cors:
    allowed_origins:
      - http://localhost:5173

decorator:
  datasource:
    p6spy:
      enable-logging: false
      logging: slf4j
      multiline: true

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 180
  refresh-token-exp-seconds: 12096000



